### ISSUE TITLE
Build a Wasm Extension with C++ is failed

### ISSUE THREAD

**Issue by xcbeyond** [istio-ecosystem/wasm-extensions#62]
Build according to [Develop a Wasm extension with C++](https://github.com/istio-ecosystem/wasm-extensions/blob/master/doc/write-a-wasm-extension-with-cpp.md)，commond `bazel build //:example.wasm`  is failed：
`ERROR: C:/users/administrator/_bazel_administrator/e2vfoios/external/proxy_wasm_cpp_sdk/toolchain/BUILD:21:10: no such package '@emscripten_toolchain//': The repository '@emscripten_toolchain' could not be resolved and referenced by '@proxy_wasm_cpp_sdk//toolchain:all'     
ERROR: Analysis of target '//:example.wasm' failed; build aborted: Analysis failed`

**Comment by ClareChu** [comment]
+1

**Comment by mark8s** [comment]
root@13:~/wasm-extensions/example# bazel build //:example.wasm
INFO: Repository proxy_wasm_cpp_sdk instantiated at:
  /root/wasm-extensions/example/WORKSPACE:9:13: in <toplevel>
Repository rule http_archive defined at:
  /root/.cache/bazel/_bazel_root/63a0e009c06f1f08983230e0fb3c8356/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in <toplevel>
WARNING: Download from https://github.com/proxy-wasm/proxy-wasm-cpp-sdk/archive/fd0be8405db25de0264bdb78fae3a82668c03782.tar.gz failed: class java.io.IOException connect timed out
ERROR: An error occurred during the fetch of repository 'proxy_wasm_cpp_sdk':
   Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/63a0e009c06f1f08983230e0fb3c8356/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/proxy-wasm/proxy-wasm-cpp-sdk/archive/fd0be8405db25de0264bdb78fae3a82668c03782.tar.gz] to /root/.cache/bazel/_bazel_root/63a0e009c06f1f08983230e0fb3c8356/external/proxy_wasm_cpp_sdk/temp504676285066786809/fd0be8405db25de0264bdb78fae3a82668c03782.tar.gz: connect timed out
ERROR: Error fetching repository: Traceback (most recent call last):
	File "/root/.cache/bazel/_bazel_root/63a0e009c06f1f08983230e0fb3c8356/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl
		download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/proxy-wasm/proxy-wasm-cpp-sdk/archive/fd0be8405db25de0264bdb78fae3a82668c03782.tar.gz] to /root/.cache/bazel/_bazel_root/63a0e009c06f1f08983230e0fb3c8356/external/proxy_wasm_cpp_sdk/temp504676285066786809/fd0be8405db25de0264bdb78fae3a82668c03782.tar.gz: connect timed out
ERROR: no such package '@proxy_wasm_cpp_sdk//bazel/dep': java.io.IOException: Error downloading [https://github.com/proxy-wasm/proxy-wasm-cpp-sdk/archive/fd0be8405db25de0264bdb78fae3a82668c03782.tar.gz] to /root/.cache/bazel/_bazel_root/63a0e009c06f1f08983230e0fb3c8356/external/proxy_wasm_cpp_sdk/temp504676285066786809/fd0be8405db25de0264bdb78fae3a82668c03782.tar.gz: connect timed out
INFO: Elapsed time: 74.668s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded)

**Comment by xcbeyond** [comment]
> # bazel build //:example.wasm
> INFO: Repository proxy_wasm_cpp_sdk instantiated at: /root/wasm-extensions/example/WORKSPACE:9:13: in Repository rule http_archive defined at: /root/.cache/bazel/_bazel_root/63a0e009c06f1f08983230e0fb3c8356/external/bazel_tools/tools/build_defs/repo/http.bzl:336:31: in WARNING: Download from https://github.com/proxy-wasm/proxy-wasm-cpp-sdk/archive/fd0be8405db25de0264bdb78fae3a82668c03782.tar.gz failed: class java.io.IOException connect timed out ERROR: An error occurred during the fetch of repository 'proxy_wasm_cpp_sdk': Traceback (most recent call last): File "/root/.cache/bazel/_bazel_root/63a0e009c06f1f08983230e0fb3c8356/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl download_info = ctx.download_and_extract( Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/proxy-wasm/proxy-wasm-cpp-sdk/archive/fd0be8405db25de0264bdb78fae3a82668c03782.tar.gz] to /root/.cache/bazel/_bazel_root/63a0e009c06f1f08983230e0fb3c8356/external/proxy_wasm_cpp_sdk/temp504676285066786809/fd0be8405db25de0264bdb78fae3a82668c03782.tar.gz: connect timed out ERROR: Error fetching repository: Traceback (most recent call last): File "/root/.cache/bazel/_bazel_root/63a0e009c06f1f08983230e0fb3c8356/external/bazel_tools/tools/build_defs/repo/http.bzl", line 111, column 45, in _http_archive_impl download_info = ctx.download_and_extract( Error in download_and_extract: java.io.IOException: Error downloading [https://github.com/proxy-wasm/proxy-wasm-cpp-sdk/archive/fd0be8405db25de0264bdb78fae3a82668c03782.tar.gz] to /root/.cache/bazel/_bazel_root/63a0e009c06f1f08983230e0fb3c8356/external/proxy_wasm_cpp_sdk/temp504676285066786809/fd0be8405db25de0264bdb78fae3a82668c03782.tar.gz: connect timed out ERROR: no such package '@proxy_wasm_cpp_sdk//bazel/dep': java.io.IOException: Error downloading [https://github.com/proxy-wasm/proxy-wasm-cpp-sdk/archive/fd0be8405db25de0264bdb78fae3a82668c03782.tar.gz] to /root/.cache/bazel/_bazel_root/63a0e009c06f1f08983230e0fb3c8356/external/proxy_wasm_cpp_sdk/temp504676285066786809/fd0be8405db25de0264bdb78fae3a82668c03782.tar.gz: connect timed out INFO: Elapsed time: 74.668s INFO: 0 processes. FAILED: Build did NOT complete successfully (0 packages loaded)

@mark8s Problem accessing githuh network

**Comment by mark8s** [comment]
@xcbeyond I just found out

**Comment by mark8s** [comment]
Build completed successfully , My OS is Ubuntu,Bazelisk version: v1.11.0

INFO: Elapsed time: 767.543s, Critical Path: 66.91s
INFO: 6 processes: 1 internal, 5 linux-sandbox.
INFO: Build completed successfully, 6 total actions
